# backend/real_converter.py – نسخه نهایی با دانلود درست و پرداخت امن غیرمستقیم از طریق رمزینکس

from flask import Flask, request, jsonify, send_from_directory
from PIL import Image, ImageFilter
import numpy as np
import os, uuid
from werkzeug.utils import secure_filename

app = Flask(__name__)

# مسیر مطلق پوشه آپلود
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
UPLOAD_FOLDER = os.path.join(BASE_DIR, 'uploads')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
MAX_FILE_SIZE = 5 * 1024 * 1024  # ۵ مگابایت
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['MAX_CONTENT_LENGTH'] = MAX_FILE_SIZE

# اطلاعات تماس (جایگزین با آیدی واقعی شما)
TELEGRAM_ID = ""   # ← آیدی تلگرام خود را اینجا بگذارید (بدون @)
EITA_ID = "Axjgc4jcxgjvxgjvxvjvxvhvxfukhg"          # ← آیدی ایتا یا شماره تماس

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def estimate_depth(image):
    gray = image.convert('L')
    laplacian = gray.filter(ImageFilter.Kernel(
        (3,3), [-1,-1,-1, -1,8,-1, -1,-1,-1], scale=1, offset=128))
    return np.array(laplacian, dtype=np.float64)

def edge_detect(image):
    gray = np.array(image.convert('L'), dtype=np.int16)
    grad_x = np.abs(np.diff(gray, axis=1))
    grad_y = np.abs(np.diff(gray, axis=0))
    h, w = gray.shape
    edge_x = np.zeros((h, w))
    edge_x[:, :w-1] = grad_x
    edge_y = np.zeros((h, w))
    edge_y[:h-1, :] = grad_y
    magnitude = np.sqrt(edge_x**2 + edge_y**2)
    edges = (magnitude > 30).astype(np.uint8) * 255
    return edges

def generate_3d_model(edges, depth):
    vertices = []
    step = 5
    h, w = edges.shape
    for y in range(0, h, step):
        for x in range(0, w, step):
            if edges[y, x] > 0:
                z = depth[y, x] * 0.05
                vertices.append([float(x), float(y), float(z)])
    if not vertices:
        vertices.append([0.0, 0.0, 0.0])
    return vertices

def create_obj_file(vertices, filepath):
    with open(filepath, 'w') as f:
        f.write("# OBJ generated by Img3D\n")
        for v in vertices:
            f.write(f"v {v[0]} {v[1]} {v[2]}\n")

@app.route('/')
def index():
    return f'''
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Img3D - تبدیل تصویر به سه‌بعدی</title>
    <style>
        body {{ font-family: Tahoma; background: #f4f4f9; padding: 20px; }}
        .container {{ max-width: 800px; margin: auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }}
        input, button {{ margin: 10px 0; }}
        button {{ background: #007bff; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; }}
        button:hover {{ background: #0056b3; }}
        .result {{ margin-top: 20px; padding: 10px; background: #e9ecef; border-radius: 5px; }}
        .payment-box {{
            background: #e8f5e9; border: 2px solid #4caf50; border-radius: 10px; padding: 20px; margin-bottom: 20px;
            text-align: center;
        }}
        .payment-box h3 {{ margin-top: 0; color: #2e7d32; }}
        .contact-links a {{
            display: inline-block; margin: 5px; padding: 10px 15px; background: #4caf50; color: white;
            text-decoration: none; border-radius: 5px; font-weight: bold;
        }}
        .note {{ font-size: 0.9em; color: #555; margin-top: 10px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Img3D</h1>
        <p>تبدیل تصاویر دوبعدی به مدل‌های سه‌بعدی (OBJ)</p>

        <!-- روش پرداخت امن -->
        <div class="payment-box">
            <h3> تهیه نسخه حرفه‌ای (بدون درگاه مستقیم)</h3>
            <p>برای دریافت مدل‌های با کیفیت بالا و پشتیبانی کامل، لطفاً با ما در ارتباط باشید.<br>
            پرداخت <strong>فقط از طریق رمزینکس</strong> (امن، بدون افشای اطلاعات مالی در سایت) انجام می‌شود.</p>
            <div class="contact-links">
                <a href="https://t.me/{TELEGRAM_ID}" target="_blank">تلگرام</a>
                <a href="https://eitaa.com/{EITA_ID}" target="_blank">ایتا</a>
            </div>
            <p class="note">پس از تماس، لینک پرداخت موقت و یکبارمصرف رمزینکس برای شما ارسال خواهد شد.</p>
        </div>

        <!-- تبدیل رایگان آزمایشی -->
        <h2>آپلود آزمایشی (رایگان)</h2>
        <form id="uploadForm" enctype="multipart/form-data">
            <input type="file" id="imageInput" name="image" accept="image/*" required>
            <button type="submit">تبدیل به 3D</button>
        </form>
        <div class="result" id="result" style="display:none;"></div>
    </div>
    <script>
        document.getElementById('uploadForm').addEventListener('submit', async (e) => {{
            e.preventDefault();
            const fd = new FormData();
            fd.append('image', document.getElementById('imageInput').files[0]);
            const res = document.getElementById('result');
            res.style.display = 'block';
            res.innerHTML = 'در حال پردازش...';
            try {{
                const resp = await fetch('/api/real-convert', {{ method:'POST', body:fd }});
                const data = await resp.json();
                if (data.success) {{
                    const downloadUrl = window.location.origin + data.model_url;
                    res.innerHTML = `✅ موفق! <a href="${{downloadUrl}}" target="_blank">دانلود فایل OBJ</a>`;
                }} else {{
                    res.innerHTML = `❌ خطا: ${{data.message}}`;
                }}
            }} catch (err) {{ res.innerHTML = '❌ خطا در ارتباط با سرور'; }}
        }});
    </script>
</body>
</html>'''

@app.route('/api/real-convert', methods=['POST'])
def real_convert():
    if 'image' not in request.files:
        return jsonify({'success': False, 'message': 'فایلی ارسال نشده'}), 400
    file = request.files['image']
    if file.filename == '' or not allowed_file(file.filename):
        return jsonify({'success': False, 'message': 'فرمت مجاز: png, jpg, jpeg, gif'}), 400

    original = secure_filename(file.filename)
    fname = f"{uuid.uuid4()}_{original}"
    filepath = os.path.join(app.config['UPLOAD_FOLDER'], fname)
    file.save(filepath)

    try:
        img = Image.open(filepath).convert('RGB')
        depth_map = estimate_depth(img)
        edges = edge_detect(img)
        vertices = generate_3d_model(edges, depth_map)

        obj_name = f"{uuid.uuid4()}.obj"
        obj_path = os.path.join(app.config['UPLOAD_FOLDER'], obj_name)
        create_obj_file(vertices, obj_path)

        return jsonify({
            'success': True,
            'model_url': f'/download/{obj_name}',
            'message': 'مدل 3D تولید شد'
        })
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)}), 500
    finally:
        pass

@app.route('/download/<filename>')
def download_file(filename):
    # ارسال فایل از مسیر مطلق (بدون مشکل 404)
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename, as_attachment=True)

if __name__ == '__main__':
    app.run(debug=False, host='0.0.0.0', port=5000)
